  - name: Install Remi repository (Alternative)
    ansible.builtin.yum:
      name: redis
      state: installed

  - name: edit redis.conf file
    ansible.builtin.replace:
      path: '/etc/redis.conf'
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: nginx start and enable
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
