  - name: Install nodejs
    ansible.builtin.import_role:
      name: common
      tasks_from: nodejs

  - name: set-up application
    ansible.builtin.import_role:
      name: common
      tasks_from: appsetup


  - name: npm install
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: systemd service
    ansible.builtin.import_role:
      name: common
      tasks_from: systemd

  - name: load data
    ansible.builtin.import_role:
      name: common
      tasks_from: loadmongodb
  




