  - name: cpoy the {{component}} service
    ansible.builtin.copy:
      src: "{{component}}.service"
      dest: /etc/systemd/system {{component}}.service

  - name: demon reload in ansible
    ansible.builtin.systemd:
      daemon_reload: true

  - name: start and enable {{component}}
    ansible.builtin.service:
      name: "{{component}}"
      state: started
      enabled: yes